baseURL = "https://wallpaperworks.app"
title = "WallpaperWorks"
author = "FrankTCA"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = ""

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = ['blog']

  googleFonts = false

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "WallpaperWorks Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "WallpaperWorks"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Revolutionary wallpapers for your desktop"
    meta_og_title = "WallpaperWorks"
    meta_og_type = "website"
    meta_og_url = "https://wallpaperworks.app"
    #meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    #meta_og_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    #meta_twitter_card = "summary_large_image"
    #meta_twitter_site = "@username"
    #meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "buy"
    name = "Buy Now"
    url = "https://www.paypal.com/ncp/payment/FF8UY6U6EQ2H8"
    weight = 1

  [[menu.main]]
    identifier = "download"
    name = "Download"
    url = "/download/"
    weight = 2

  [[menu.main]]
    identifier = "demo"
    name = "Web Demo"
    url = "https://infotoast.org/homepage/"
    weight = 3

  [[menu.main]]
    identifier = "images"
    name = "Images"
    url = "/images/"
    weight = 4

  [[menu.main]]
    identifier = "opensource"
    name = "Open Source"
    url = "https://github.com/Aaron-Speedy/WallpaperWorks"
    weight = 5

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 6

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/Aaron-Speedy/WallpaperWorks"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2

  [[menu.footer]]
    name = "We use the Mallory font!"
    url = "https://frerejones.com/families/mallory"
    weight = 3
